version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://booksdb_uoqj_user:LCNvLkjcjMRuzIreNax4Yq54hUKNwwIe@dpg-cr9vqp23esus739ooan0-a.oregon-postgres.render.com/booksdb_uoqj

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://booksdb_uoqj_user:LCNvLkjcjMRuzIreNax4Yq54hUKNwwIe@dpg-cr9vqp23esus739ooan0-a.oregon-postgres.render.com/booksdb_uoqj
