---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: booksapp.azurecr.io/book-catalog
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgresql://booksdb_g0y0_user:2Q5y61WAibBzvNJ2bPv50E372B8lc69s@dpg-cr94osogph6c73cqe0gg-a.oregon-postgres.render.com/booksdb_g0y0"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort  
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80  # Cluster-wide port that the service will listen on
      targetPort: 8082  # Port on which the container listens
      nodePort: 30082  # External port on the node (must be between 30000-32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: booksapp.azurecr.io/inventory-management
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgresql://booksdb_g0y0_user:2Q5y61WAibBzvNJ2bPv50E372B8lc69s@dpg-cr94osogph6c73cqe0gg-a.oregon-postgres.render.com/booksdb_g0y0"  
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: NodePort  # Exposes the service using NodePort
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 81  # Cluster-wide port that the service will listen on
      targetPort: 8081  # Port on which the container listens
      nodePort: 30081  # External port on the node (must be between 30000-32767)
